type: markdown
css: |
  @import url('https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@300;400;600;700&family=Instrument+Serif:opsz,wght@8..144,500;600&family=JetBrains+Mono:wght@400;600&display=swap');

  .markdown-note {
    --md-accent: #2563eb;
    --md-accent-strong: #1d4ed8;
    --md-surface: #ffffff;
    --md-soft: color-mix(in srgb, #2563eb 10%, transparent);
    --md-border: color-mix(in srgb, #2563eb 18%, #e2e8f0);
    --md-muted: color-mix(in srgb, currentColor 65%, transparent);
    font-family: "Instrument Sans", "Segoe UI", sans-serif;
    font-size: 16px;
    line-height: 1.72;
    color: var(--shell-text, #0f172a);
    max-width: 880px;
    margin: 0 auto;
  }
  .markdown-note h1,
  .markdown-note h2,
  .markdown-note h3,
  .markdown-note h4 {
    font-family: "Instrument Serif", "Times New Roman", serif;
    line-height: 1.2;
    margin: 1.6em 0 0.6em;
    letter-spacing: -0.01em;
  }
  .markdown-note h1 { font-size: 2.45rem; }
  .markdown-note h2 { font-size: 1.9rem; }
  .markdown-note h3 { font-size: 1.4rem; }
  .markdown-note h4 {
    font-size: 1.1rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }
  .markdown-note p { margin: 0 0 1.05em; }
  .markdown-note ul,
  .markdown-note ol {
    margin: 0 0 1.05em;
    padding-left: 1.3em;
  }
  .markdown-note li + li { margin-top: 0.25em; }
  .markdown-note a {
    color: color-mix(in srgb, var(--md-accent) 85%, currentColor);
    text-decoration: underline;
    text-decoration-thickness: 0.12em;
    text-underline-offset: 0.2em;
  }
  .markdown-note a:hover {
    color: color-mix(in srgb, var(--md-accent-strong) 85%, currentColor);
  }
  .markdown-note blockquote {
    border-left: 3px solid var(--md-accent);
    padding: 0.85em 1.1em;
    margin: 1.3em 0;
    color: var(--md-muted);
    background: color-mix(in srgb, var(--md-accent) 7%, transparent);
    border-radius: 0.7rem;
  }
  .markdown-note code {
    font-family: "JetBrains Mono", "Fira Mono", monospace;
    font-size: 0.92em;
    padding: 0.12em 0.35em;
    border-radius: 0.3rem;
    background: color-mix(in srgb, var(--md-accent) 12%, transparent);
  }
  .markdown-note pre {
    margin: 1.2em 0;
    padding: 1em 1.1em;
    border-radius: 0.85rem;
    border: 1px solid var(--md-border);
    background: color-mix(in srgb, #0f172a 6%, transparent);
    overflow-x: auto;
  }
  .markdown-note pre code {
    display: block;
    padding: 0;
    background: transparent;
  }
  .markdown-note table {
    width: 100%;
    border-collapse: collapse;
    margin: 1.4em 0;
    font-size: 0.98em;
  }
  .markdown-note th,
  .markdown-note td {
    border: 1px solid color-mix(in srgb, var(--md-border) 70%, currentColor 25%);
    padding: 0.65em 0.85em;
    text-align: left;
  }
  .markdown-note th {
    text-transform: uppercase;
    letter-spacing: 0.04em;
    font-size: 0.9em;
    background: color-mix(in srgb, var(--md-accent) 8%, transparent);
  }
  .markdown-note hr {
    border: none;
    border-top: 1px solid color-mix(in srgb, var(--md-border) 75%, currentColor 25%);
    margin: 2em 0;
  }
  .markdown-note figure {
    margin: 1.6rem auto;
    text-align: center;
  }
  .markdown-note figcaption {
    margin-top: 0.6rem;
    font-size: 0.92rem;
    color: var(--md-muted);
  }
  .markdown-note img {
    max-width: min(100%, 780px);
    border-radius: 1rem;
    border: 1px solid color-mix(in srgb, var(--md-border) 60%, transparent);
    box-shadow: 0 16px 42px rgba(15, 23, 42, 0.16);
  }
  .markdown-note .markdown-callout {
    border-radius: 0.9rem;
    border: 1px solid color-mix(in srgb, var(--md-accent) 28%, currentColor 18%);
    padding: 1rem 1.2rem;
    margin: 1.3rem 0;
    background: color-mix(in srgb, var(--md-accent) 6%, transparent);
  }
  .markdown-note .markdown-callout-title {
    font-weight: 700;
    letter-spacing: 0.03em;
    margin-bottom: 0.45rem;
  }
  .markdown-note .markdown-qa {
    border: 1px solid color-mix(in srgb, var(--md-border) 70%, currentColor 30%);
    border-radius: 1rem;
    padding: 0.9rem 1.1rem;
    margin: 1.1rem 0;
    background: color-mix(in srgb, var(--md-accent) 6%, transparent);
    box-shadow: 0 16px 32px rgba(15, 23, 42, 0.1);
  }
  .markdown-note .markdown-qa .markdown-qa-label {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 22px;
    height: 22px;
    margin-right: 8px;
    border-radius: 50%;
    background: color-mix(in srgb, var(--md-accent) 18%, transparent);
    font-weight: 700;
    font-size: 0.85rem;
  }
  .markdown-note details.markdown-qa summary {
    cursor: pointer;
    list-style: none;
  }
  .markdown-note details.markdown-qa summary::-webkit-details-marker {
    display: none;
  }
  .markdown-note .markdown-qa-toggle {
    margin-left: auto;
    font-size: 0.8rem;
    color: var(--md-muted);
  }
  .markdown-note .markdown-media {
    margin: 1rem 0;
    border-radius: 0.9rem;
    background: color-mix(in srgb, var(--md-accent) 8%, transparent);
    padding: 0.9rem 1rem;
    box-shadow: 0 14px 28px rgba(15, 23, 42, 0.12);
  }
  .markdown-note .markdown-media audio,
  .markdown-note .markdown-media video {
    width: 100%;
    display: block;
    border-radius: 0.75rem;
    outline: none;
    background: #0b1224;
  }
  .markdown-note .markdown-media .markdown-media-caption {
    margin-top: 0.6rem;
    font-size: 0.92rem;
    color: var(--md-muted);
  }
  .markdown-note .markdown-img-grid {
    display: grid;
    gap: clamp(10px, 1.2vw, 16px);
    margin: 1.1rem 0;
  }
  .markdown-note .markdown-img-grid img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .markdown-note .markdown-img-grid.two-col,
  .markdown-note .markdown-img-grid.two-vertical {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
  .markdown-note .markdown-img-grid.four-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
  .markdown-note .markdown-img-grid.rail {
    grid-auto-flow: column;
    grid-auto-columns: minmax(200px, 1fr);
    overflow-x: auto;
    padding-bottom: 6px;
  }
  .markdown-note .markdown-cover {
    padding: 3rem 2rem;
    border-radius: 1.4rem;
    background: linear-gradient(135deg, rgba(37, 99, 235, 0.12), rgba(15, 23, 42, 0.04));
    text-align: center;
  }
  .markdown-note .markdown-divider {
    text-align: center;
    padding: 1.2rem 0;
  }
  .markdown-note .markdown-divider::before {
    content: "";
    display: block;
    height: 1px;
    background: color-mix(in srgb, var(--md-border) 75%, currentColor 25%);
    margin: 0.8rem auto 0;
    max-width: 55%;
  }
  .markdown-note .markdown-banner {
    padding: 1rem 1.2rem;
    border-radius: 0.9rem;
    background: color-mix(in srgb, var(--md-accent) 10%, transparent);
  }
  .markdown-note .markdown-notes {
    font-size: 0.92rem;
    color: var(--md-muted);
    border-left: 3px solid color-mix(in srgb, var(--md-accent) 30%, currentColor 20%);
    padding: 0.65rem 0.9rem;
  }
  .markdown-note .markdown-kpi,
  .markdown-note .markdown-features {
    display: grid;
    gap: 1rem;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    margin: 1.2rem 0;
  }
  .markdown-note .markdown-kpi > *,
  .markdown-note .markdown-features > * {
    background: color-mix(in srgb, var(--md-accent) 8%, #ffffff);
    border: 1px solid color-mix(in srgb, var(--md-accent) 18%, transparent);
    border-radius: 0.9rem;
    padding: 1rem 1.1rem;
    box-shadow: 0 16px 32px rgba(15, 23, 42, 0.08);
  }
  .markdown-note .markdown-cols {
    display: grid;
    gap: 1rem;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    margin: 1.1rem 0;
  }
  .markdown-note .markdown-cols > * {
    margin: 0;
  }
  .markdown-note .markdown-code-split {
    display: grid;
    gap: 1rem;
    grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
    align-items: start;
    margin: 1.3rem 0;
  }
  .markdown-note .markdown-code-split pre {
    margin: 0;
  }
  .markdown-note .markdown-highlight {
    background: color-mix(in srgb, var(--md-accent) 18%, transparent);
    border-radius: 0.3rem;
    padding: 0 0.25rem;
  }
  .markdown-note .markdown-blur {
    filter: blur(4px);
    transition: filter 0.2s ease;
  }
  .markdown-note .markdown-blur:hover,
  .markdown-note .markdown-blur:focus {
    filter: blur(0);
  }
wrapperClass: markdown-note
exportCss: |
  body.markdown-export {
    background:
      radial-gradient(circle at 15% 10%, rgba(59, 130, 246, 0.12), transparent 45%),
      radial-gradient(circle at 85% 0%, rgba(14, 165, 233, 0.08), transparent 55%),
      linear-gradient(180deg, #f8fafc 0%, #eef2f7 100%);
    color: #0f172a;
    font-family: "Instrument Sans", "Segoe UI", sans-serif;
    margin: 0;
  }
  body.markdown-export .markdown-export-content {
    max-width: 920px;
    margin: 48px auto;
    padding: 54px 60px;
    background: #ffffff;
    border: 1px solid #e5e7eb;
    border-radius: 24px;
    box-shadow: 0 28px 70px rgba(15, 23, 42, 0.12);
    animation: md-default-rise 0.55s ease-out both;
  }
  body.markdown-export .markdown-note {
    color: inherit;
  }
  body.markdown-export pre {
    position: relative;
    padding-top: 2.6rem;
  }
  .md-progress {
    position: fixed;
    top: 0;
    left: 0;
    height: 4px;
    width: 0;
    background: linear-gradient(90deg, #2563eb, #0ea5e9);
    z-index: 9999;
    box-shadow: 0 0 12px rgba(14, 165, 233, 0.6);
  }
  .md-copy-btn {
    position: absolute;
    top: 0.6rem;
    right: 0.6rem;
    border: 1px solid rgba(15, 23, 42, 0.12);
    background: rgba(255, 255, 255, 0.92);
    color: #0f172a;
    font-size: 0.8rem;
    padding: 0.25rem 0.6rem;
    border-radius: 999px;
    cursor: pointer;
  }
  .md-copy-btn:hover {
    border-color: rgba(37, 99, 235, 0.4);
    color: #1d4ed8;
  }
  @keyframes md-default-rise {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
  }
  @media (prefers-reduced-motion: reduce) {
    body.markdown-export .markdown-export-content {
      animation: none;
    }
  }
customHead: |
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@300;400;600;700&family=Instrument+Serif:opsz,wght@8..144,500;600&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
customBody: |
  <script>
  (() => {
    const root = document.querySelector('.markdown-export-content');
    if (!root) return;

    const bar = document.createElement('div');
    bar.className = 'md-progress';
    document.body.appendChild(bar);

    const updateProgress = () => {
      const scrollTop = document.documentElement.scrollTop || document.body.scrollTop || 0;
      const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
      const ratio = height > 0 ? Math.min(scrollTop / height, 1) : 0;
      bar.style.width = `${Math.round(ratio * 100)}%`;
    };

    const copyText = async (text) => {
      try {
        if (navigator.clipboard && navigator.clipboard.writeText) {
          await navigator.clipboard.writeText(text);
          return true;
        }
      } catch (err) {
        // ignore
      }
      const helper = document.createElement('textarea');
      helper.value = text;
      helper.style.position = 'fixed';
      helper.style.opacity = '0';
      document.body.appendChild(helper);
      helper.focus();
      helper.select();
      try {
        const ok = document.execCommand('copy');
        helper.remove();
        return ok;
      } catch (err) {
        helper.remove();
        return false;
      }
    };

    root.querySelectorAll('pre').forEach(pre => {
      const code = pre.querySelector('code');
      if (!code) return;
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'md-copy-btn';
      btn.textContent = 'Copy';
      btn.addEventListener('click', async () => {
        const ok = await copyText(code.textContent || '');
        btn.textContent = ok ? 'Copied' : 'Copy';
        setTimeout(() => { btn.textContent = 'Copy'; }, 1600);
      });
      pre.appendChild(btn);
    });

    updateProgress();
    window.addEventListener('scroll', updateProgress, {passive: true});
  })();
  </script>
